#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Basılı sürüm dışa aktarımı — BASKI.md'deki P1 adımı.

Atlas-Kitap.dc.html (TR) ve Atlas-Kitap-EN.dc.html (EN) içindeki modules() verisini node ile
değerlendirir ve yazarın genişleteceği kaynak dosyaları üretir:

  print/src/<dil>/M01-….md … M08-….md   bölüm başına Markdown: basit, teknik, kenar notu, şekil bloğu
                                        iskeleti (Kurulum / Adım adım / Ne oluyor? / Kendin dene),
                                        demo verisi tabloları, demoya gömülü metinler, quiz
  print/src/<dil>/book.json              aynı verinin ham hâli (figür üretimi için)
  print/src/<dil>/cevap-anahtari.md      quiz + "kendini sına" demoları için cevap anahtarı
  print/src/<dil>/demo-gomulu-metinler.md renderVals() içine gömülü, yalnız etkileşimden sonra görünen
                                        öğretici metinlerin demo başına listesi

Kullanım:
  python3 print/export.py            # yalnız eksik dosyaları üretir (yazar genişletmeleri korunur)
  python3 print/export.py --force    # M*.md dosyalarını da yeniden üretir (elle yapılan işi SİLER)
  python3 print/export.py --lang tr  # tek dil

book.json, cevap anahtarı ve gömülü metin listesi her çalıştırmada yenilenir; bunlar elle düzenlenmez.
"""
import json
import os
import re
import subprocess
import sys
import tempfile
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'print', 'src')
SOURCES = {
    'tr': os.path.join(ROOT, 'Atlas-Kitap.dc.html'),
    'en': os.path.join(ROOT, 'Atlas-Kitap-EN.dc.html'),
}
LIVE = {'tr': 'https://book.onuronder.com/d/', 'en': 'https://book.onuronder.com/d/en/'}  # + qr-slugs.json slug
_SLUG_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'qr-slugs.json')
SLUGS = json.load(open(_SLUG_PATH, encoding='utf-8')) if os.path.exists(_SLUG_PATH) else {}

# BASKI.md §4: S = statik seçim→sonuç, A = adımlı dizi (film şeridi), Z = zamanlayıcıya bağlı
DEMO_KIND = {
    'intelligence': 'S', 'binary': 'S', 'turing': 'Z', 'cycle': 'Z', 'classify': 'S', 'exp': 'A',
    'chain': 'A', 'expert': 'S', 'grid': 'Z', 'markov': 'Z',
    'spam': 'S', 'scatter': 'A', 'kmeans': 'A', 'descent': 'Z', 'modelfit': 'S',
    'neuron': 'S', 'ffnet': 'A', 'backprop': 'A', 'conv': 'A', 'rnn': 'A', 'gan': 'A',
    'token': 'S', 'embed': 'S', 'attn': 'S', 'generate': 'A', 'train': 'S', 'diffuse': 'A', 'ctx': 'A',
    'prompt': 'S', 'rag': 'S', 'agent': 'A', 'arch': 'S', 'sector': 'S',
    'bias': 'S', 'explain': 'S', 'df': 'A', 'reg': 'S', 'align': 'S',
    'tur': 'A', 'chineseroom': 'A', 'capability': 'S', 'singularity': 'S', 'responsibility': 'S',
}
# Cevapları demoya gömülü olan "kendini sına" demoları (cevap anahtarında elle doldurulacak)
SELF_TEST_EMBEDDED = {'df', 'reg', 'tur', 'responsibility'}

T = {
    'tr': dict(
        generated='Bu dosya print/export.py tarafından üretildi', lang_note='Genişletmeler bu dosyada yapılır; '
        'export yeniden çalıştırıldığında --force verilmedikçe üzerine yazılmaz.',
        accent='aksan', live='canlı demo', margin='Kenar notu', simple='Basit', tech='Teknik ▸',
        figure='Şekil', setup='Kurulum', steps='Adım adım', what_s='Ne oluyor? (Basit)', what_t='Ne oluyor? (Teknik ▸)',
        try_='Kendin dene', todo='[YAZILACAK]', hint='Ekrandaki ipucu', data='Demo verisi',
        embedded='Demoya gömülü metinler (yalnız etkileşimden sonra görünür; düzyazıya taşınacak)',
        bridge='Geçiş cümlesi', takeaways='Bu bölümden kalanlar', takeaways_todo='[YAZILACAK: 5–7 madde]',
        quiz='Kendini test et', answers='Cevaplar', answers_file='cevap-anahtari.md',
        embedded_file='demo-gomulu-metinler.md', key_title='Cevap anahtarı', key_quiz='Bölüm sonu quizleri',
        key_self='Kendini sına demoları', key_manual='cevap demoya gömülü; bkz. demo-gomulu-metinler.md, elle yazılacak',
        emb_title='Demolara gömülü öğretici metinler', kind='tip', none='—',
        deep_link_note='Not: derin bağlantı (#m=N&s=K) çalışma zamanında henüz desteklenmiyor; QR öncesi eklenecek.',
        legend='S = statik seçim→sonuç · A = adımlı dizi (film şeridi) · Z = zamanlayıcıya bağlı (çok panel zorunlu)',
    ),
    'en': dict(
        generated='This file was generated by print/export.py', lang_note='Expand the text in this file; '
        're-running export will not overwrite it unless --force is given.',
        accent='accent', live='live demo', margin='Margin note', simple='Simple', tech='Technical ▸',
        figure='Figure', setup='Setup', steps='Step by step', what_s='What is happening? (Simple)',
        what_t='What is happening? (Technical ▸)', try_='Try it yourself', todo='[TO WRITE]', hint='On-screen hint',
        data='Demo data', embedded='Text embedded in the demo (visible only after interaction; move into prose)',
        bridge='Bridge sentence', takeaways='Key takeaways', takeaways_todo='[TO WRITE: 5–7 bullets]',
        quiz='Test yourself', answers='Answers', answers_file='answer-key.md',
        embedded_file='demo-embedded-texts.md', key_title='Answer key', key_quiz='End-of-chapter quizzes',
        key_self='Self-test demos', key_manual='answer is embedded in the demo; see demo-embedded-texts.md, write by hand',
        emb_title='Teaching text embedded in demos', kind='kind', none='—',
        deep_link_note='Note: deep links (#m=N&s=K) are not yet supported by the runtime; add before printing QR codes.',
        legend='S = static pick→result · A = stepped sequence (film strip) · Z = timer-driven (multi-panel required)',
    ),
}

TR_MAP = str.maketrans('çğıöşüÇĞİÖŞÜâîû', 'cgiosuCGIOSUaiu')


def slug(s):
    s = s.translate(TR_MAP).lower()
    s = re.sub(r'[^a-z0-9]+', '-', s).strip('-')
    return s


# ---------------------------------------------------------------- kaynak okuma

def eval_modules(html):
    m = re.search(r"\n  modules\(\) \{\n(.*?)\n  \}\n\n  upcoming\(\)", html, re.S)
    if not m:
        sys.exit('modules() bloğu bulunamadı')
    js = 'const modules=function(){\n' + m.group(1) + '\n};process.stdout.write(JSON.stringify(modules()));'
    with tempfile.NamedTemporaryFile('w', suffix='.js', delete=False, encoding='utf-8') as f:
        f.write(js)
        path = f.name
    try:
        res = subprocess.run(['node', path], capture_output=True, text=True, check=True)
    finally:
        os.unlink(path)
    return json.loads(res.stdout)


def order(seed, n):
    """Atlas-Kitap.dc.html _order(): quiz seçeneklerinin deterministik karışımı. Basılı sürümde seed = soru indeksi + 10 × bölüm no
    (web kitabında seed = soru indeksi; her bölümde aynı harf deseni çıktığı için basılıda bölüme göre değişir)."""
    arr = list(range(n))
    r = (seed + 3) * 2654435761 % 2147483647
    for i in range(n - 1, 0, -1):
        r = (r * 16807) % 2147483647
        j = r % (i + 1)
        arr[i], arr[j] = arr[j], arr[i]
    return arr


STR_RE = re.compile(r"'((?:[^'\\\n]|\\.)*)'|\"((?:[^\"\\\n]|\\.)*)\"|`((?:[^`\\]|\\.)*)`", re.S)
CSSY = re.compile(r"\d+px|rgba?\(|#[0-9a-fA-F]{3,6}\b|font-|transition|margin|padding|border|display:|width:|height:"
                  r"|linear-gradient|flex|cursor|opacity:|letter-spacing|text-transform|position:|overflow")


def unescape(s):
    s = re.sub(r'\\u([0-9a-fA-F]{4})', lambda m: chr(int(m.group(1), 16)), s)
    return s.replace("\\'", "'").replace('\\"', '"').replace('\\n', ' ').replace('\\\\', '\\')


def embedded_texts(html):
    """renderVals() içindeki demo dallarından, UI etiketi olmayan uzun metin sabitlerini çıkarır."""
    start = html.index('\n  renderVals() {')
    end = html.index('\n  _order(', start)
    region = html[start:end]
    marks = [(m.start(), m.group(1)) for m in re.finditer(r"demo\.type === '([a-z0-9]+)'", region)]
    quiz_at = region.find('// shuffle deterministically')
    result = {}
    for i, (pos, typ) in enumerate(marks):
        nxt = marks[i + 1][0] if i + 1 < len(marks) else (quiz_at if quiz_at > pos else len(region))
        chunk = region[pos:nxt]
        found = []
        for m in STR_RE.finditer(chunk):
            s = unescape(next(g for g in m.groups() if g is not None)).strip()
            if len(s) < 18 or ' ' not in s or not re.search(r'[A-Za-zçğıöşüÇĞİÖŞÜ]', s):
                continue
            if CSSY.search(s) or s.startswith('${'):
                continue
            if s not in found:
                found.append(s)
        if found:
            result.setdefault(typ, []).extend(x for x in found if x not in result.get(typ, []))
    return result


# ---------------------------------------------------------------- markdown yardımcıları

def md_table(rows, cols=None):
    if not rows:
        return ''
    if cols is None:
        cols = []
        for r in rows:
            for k in r:
                if k not in cols:
                    cols.append(k)
    esc = lambda v: str(v).replace('|', '\\|').replace('\n', ' ')
    out = ['| ' + ' | '.join(cols) + ' |', '|' + '---|' * len(cols)]
    for r in rows:
        out.append('| ' + ' | '.join(esc(r.get(c, '')) if isinstance(r, dict) else esc(r) for c in cols) + ' |')
    return '\n'.join(out)


def render_data(demo):
    """Demo nesnesindeki veri alanlarını (types, items, rules, matrix …) Markdown'a çevirir."""
    skip = {'type', 'title', 'hint', 'hintBasit', 'neOluyor', 'neOluyorBasit'}
    parts = []
    for k, v in demo.items():
        if k in skip:
            continue
        if isinstance(v, list) and v and all(isinstance(x, dict) for x in v):
            parts.append(f'**{k}**\n\n' + md_table(v))
        elif isinstance(v, list) and v and all(isinstance(x, list) for x in v):
            parts.append(f'**{k}**\n\n' + md_table([{str(i): c for i, c in enumerate(row)} for row in v]))
        elif isinstance(v, list):
            parts.append(f'**{k}**: ' + ', '.join(str(x) for x in v))
        elif isinstance(v, dict):
            parts.append(f'**{k}**: ' + ', '.join(f'{a}={b}' for a, b in v.items()))
        else:
            parts.append(f'**{k}**: {v}')
    return '\n\n'.join(parts)


# ---------------------------------------------------------------- bölüm dosyası

def module_md(lang, mod, mi, emb):
    t = T[lang]
    n = int(mod['n'])
    L = []
    L.append(f"# {mod['n']} · {mod['tag']} — {mod['title']}")
    L.append(f"_{mod['subtitle']}_ · {t['accent']} `{mod['acc']}`")
    L.append('')
    L.append(f"<!-- {t['generated']} ({date.today().isoformat()}). {t['lang_note']} -->")
    L.append(f"<!-- {t['legend']} -->")
    L.append('')
    fig = 0
    for si, sec in enumerate(mod['sections']):
        is_quiz = bool(sec.get('quiz'))
        L.append(f"## {n}.{si + 1} {sec['h2']}")
        link = f"{LIVE[lang]}{SLUGS.get(lang, {}).get(f'{n}.{fig + 1}', '?')}" if sec.get('demo') else '-'

        L.append(f"`id: {sec['id']}` · `{sec['label']}` · {t['live']}: <{link}>")
        L.append('')
        if is_quiz:
            L.append(f"_{t['answers']}: {t['answers_file']}_")
            L.append('')
            for qi, q in enumerate(sec['quiz']):
                L.append(f"{qi + 1}. {q['q']}")
                for pos, oi in enumerate(order(qi * 7 + 13 * int(mod["n"]) + 5, len(q["opts"]))):
                    L.append(f"   {chr(97 + pos)}) {q['opts'][oi]}")
                L.append('')
            continue
        if sec.get('tip'):
            L.append(f"> **{t['margin']}.** {sec['tip']}")
            L.append('')
        L.append(f"### {t['simple']}")
        L.append('')
        for p in sec.get('basit', []):
            L.append(p)
            L.append('')
        L.append(f"### {t['tech']}")
        L.append('')
        for p in sec.get('teknik', []):
            L.append(p)
            L.append('')
        demo = sec.get('demo')
        if demo:
            fig += 1
            kind = DEMO_KIND.get(demo['type'], '?')
            L.append(f"### {t['figure']} {n}.{fig} — {demo['title']}")
            L.append(f"`demo: {demo['type']}` · {t['kind']} **{kind}**")
            L.append('')
            hint = demo.get('hintBasit') or demo.get('hint', '')
            L.append(f"**{t['setup']}** — _{t['todo']}_  ")
            L.append(f"_{t['hint']}: {hint}_")
            L.append('')
            L.append(f"**{t['steps']}** — _{t['todo']}_")
            L.append('')
            L.append(f"**{t['what_s']}** — {demo.get('neOluyorBasit', demo.get('neOluyor', ''))}")
            L.append('')
            L.append(f"**{t['what_t']}** — {demo.get('neOluyor', '')}")
            L.append('')
            L.append(f"**{t['try_']}** — _{t['todo']}_ · QR → <{link}>")
            L.append('')
            data = render_data(demo)
            if data:
                L.append(f"<details><summary>{t['data']}</summary>")
                L.append('')
                L.append(data)
                L.append('')
                L.append('</details>')
                L.append('')
            texts = emb.get(demo['type'])
            if texts:
                L.append(f"**{t['embedded']}**")
                L.append('')
                for s in texts:
                    L.append(f"- {s}")
                L.append('')
        L.append(f"_{t['bridge']}: {t['todo']}_")
        L.append('')
    L.append(f"## {t['takeaways']}")
    L.append('')
    L.append(f"_{t['takeaways_todo']}_")
    L.append('')
    return '\n'.join(L)


def answer_key_md(lang, data):
    t = T[lang]
    L = [f"# {t['key_title']}", '', f"<!-- {t['generated']} ({date.today().isoformat()}); elle düzenlenmez. -->", '',
         f"## {t['key_quiz']}", '']
    for mod in data:
        n = int(mod['n'])
        for si, sec in enumerate(mod['sections']):
            if not sec.get('quiz'):
                continue
            L.append(f"### {mod['n']} · {mod['title']}")
            L.append('')
            for qi, q in enumerate(sec['quiz']):
                o = order(qi * 7 + 13 * int(mod["n"]) + 5, len(q["opts"]))
                letter = chr(97 + o.index(0))
                L.append(f"{n}.{si + 1} / {qi + 1}: **{letter}** · {q['opts'][0]}")
                L.append('')  # her cevap ayrı paragraf (uzun tire yok: stil kılavuzu)
    L.append(f"## {t['key_self']}")
    L.append('')
    for mod in data:
        n = int(mod['n'])
        fig = 0
        for sec in mod['sections']:
            demo = sec.get('demo')
            if not demo:
                continue
            fig += 1
            if demo['type'] == 'classify':
                cats = demo.get('cats') or [demo['catA'], demo['catB']]
                lab = {c['key']: c['label'] for c in cats}
                L.append(f"### {t['figure']} {n}.{fig} — {demo['title']}")
                L.append('')
                L.append(md_table([{'#': i + 1, 'item': it['label'], 'answer': lab.get(it['cat'], it['cat'])}
                                   for i, it in enumerate(demo['items'])]))
                L.append('')
            elif demo['type'] in SELF_TEST_EMBEDDED:
                L.append(f"### {t['figure']} {n}.{fig} — {demo['title']}")
                L.append('')
                L.append(f"_{t['todo']}: {t['key_manual']}_")
                L.append('')
    return '\n'.join(L)


def embedded_md(lang, data, emb):
    t = T[lang]
    L = [f"# {t['emb_title']}", '', f"<!-- {t['generated']} ({date.today().isoformat()}); elle düzenlenmez. -->", '']
    total = 0
    for mod in data:
        n = int(mod['n'])
        fig = 0
        for sec in mod['sections']:
            demo = sec.get('demo')
            if not demo:
                continue
            fig += 1
            texts = emb.get(demo['type'], [])
            L.append(f"## {t['figure']} {n}.{fig} — {demo['title']} (`{demo['type']}`)")
            L.append('')
            if not texts:
                L.append(t['none'])
            for s in texts:
                L.append(f"- {s}")
                total += len(s)
            L.append('')
    L.insert(3, f"_{sum(len(v) for v in emb.values())} parça · {total} karakter_")
    return '\n'.join(L)


# ---------------------------------------------------------------- ana akış

def export(lang, force):
    t = T[lang]
    html = open(SOURCES[lang], encoding='utf-8').read()
    data = eval_modules(html)
    emb = embedded_texts(html)
    out = os.path.join(OUT, lang)
    os.makedirs(out, exist_ok=True)

    with open(os.path.join(out, 'book.json'), 'w', encoding='utf-8') as f:
        json.dump({'lang': lang, 'source': os.path.basename(SOURCES[lang]), 'modules': data, 'embedded': emb},
                  f, ensure_ascii=False, indent=1)

    written, kept = [], []
    for mi, mod in enumerate(data, 1):
        path = os.path.join(out, f"M{mod['n']}-{slug(mod['title'])}.md")
        if os.path.exists(path) and not force:
            kept.append(os.path.basename(path))
            continue
        with open(path, 'w', encoding='utf-8') as f:
            f.write(module_md(lang, mod, mi, emb))
        written.append(os.path.basename(path))

    with open(os.path.join(out, t['answers_file']), 'w', encoding='utf-8') as f:
        f.write(answer_key_md(lang, data))
    with open(os.path.join(out, t['embedded_file']), 'w', encoding='utf-8') as f:
        f.write(embedded_md(lang, data, emb))

    n_sec = sum(len(m['sections']) for m in data)
    n_demo = sum(1 for m in data for s in m['sections'] if s.get('demo'))
    n_quiz = sum(len(s.get('quiz', [])) for m in data for s in m['sections'])
    print(f"[{lang}] {len(data)} modül, {n_sec} bölüm, {n_demo} demo, {n_quiz} quiz sorusu, "
          f"{sum(len(v) for v in emb.values())} gömülü metin parçası")
    print(f"      yazıldı: {', '.join(written) or '-'}")
    if kept:
        print(f"      korundu (--force ile yenilenir): {', '.join(kept)}")
    print(f"      {t['deep_link_note']}")


if __name__ == '__main__':
    force = '--force' in sys.argv
    langs = ['tr', 'en']
    if '--lang' in sys.argv:
        langs = [sys.argv[sys.argv.index('--lang') + 1]]
    for lang in langs:
        export(lang, force)
