// Bölüm 2 figür etiketleri ve gömülü verileri (tr / en). Bkz. strings/README.md.
// TR: gen/M02.mjs'nin önceki sabitleriyle birebir. EN: Atlas-Kitap-EN.dc.html renderVals() (chain/expert/grid/markov) + şablonlar;
// figür-özel etiketler (lejant, sayaçlar, .md başlıkları) burada İngilizceleştirildi.
export default {
  tr: {
    chain: {
      kb: (n) => `BİLGİ TABANI · ${n} BAĞ (“bir …dır”)`,
      link: 'bir',
      query: (k) => `SORU ${k}`,
      walked: (n) => `${n} ok izlendi`,
      walkedEnd: (n) => `${n} ok izlendi · zincir bitti`,
      yes: (target) => `✓ Evet: “${target}” zincirde bulundu (geçişlilik).`,
      unknown: (target) => `✗ Bilinmiyor: “${target}” bilgi tabanında yok.`,
      mdChain: 'Zincir',
      mdHead: '| Soru | İzlenen ok | Karar |',
      mdEnd: (n) => `${n}, zincir bitti`,
      mdYes: 'Evet',
      mdUnknown: 'Bilinmiyor',
    },
    expert: {
      facts: 'OLGULAR · SENARYO A',
      if: 'EĞER',
      then: 'O ZAMAN',
      chain: 'zincir',
      advice: 'SİSTEM ÖNERİSİ',
      three: 'ÜÇ SENARYO',
      cols: ['Senaryo', 'Açık olgular', 'Ateşlenen', 'Öneri satırı'],
      short: { yagmur: 'Yağmur', soguk: 'Soğuk', ruzgar: 'Rüzgâr' },
      scen: ['A (başlangıç)', 'B', 'C'],
      mdHead: '| Senaryo | Açık olgular | Ateşlenen kurallar | Öneri satırı |',
      mdNote: '> Kural ve öneri metinlerindeki emojiler basılı figürde atıldı.',
    },
    grid: {
      bfs: 'SEZGİSİZ (BFS)',
      greedy: 'SEZGİSEL (HEDEFE)',
      start: 'S',
      goal: 'H',
      explored: (n) => `İncelenen: ${n}`,
      pathLen: (cells, steps) => `Yol uzunluğu: ${cells} kare (${steps} adım)`,
      legend: { visited: 'taranan', path: 'bulunan yol', wall: 'duvar' },
      legendSG: 'S başlangıç · H hedef',
      note: 'Karedeki sayı: tarama sırası (1 = S). Sütun/satır numaraları 1’den başlar.',
      mdGrid: 'Izgara 8×6, S=(1,1), H=(8,6); duvarlar (sütun,satır): ',
      mdHead: '| Yöntem | Taranan kare | Yol (kare) | Adım |',
      mdBfs: 'Sezgisiz (BFS)',
      mdGreedy: 'Sezgisel (hedefe)',
      mdOrderBfs: 'BFS tarama sırası',
      mdOrderGreedy: 'Açgözlü tarama sırası',
      mdPath: 'Yol',
    },
    markov: {
      matrix: 'Geçiş matrisi (%)',
      today: 'bugün',
      tomorrow: 'yarın',
    },
  },
  en: {
    chain: {
      kb: (n) => `KNOWLEDGE BASE · ${n} LINKS (“is a …”)`,
      link: 'is a',
      query: (k) => `QUERY ${k}`,
      walked: (n) => `${n} arrows followed`,
      walkedEnd: (n) => `${n} arrows followed · chain ended`,
      yes: (target) => `✓ Yes: “${target}” found in the chain (transitivity).`,
      unknown: (target) => `✗ Unknown: “${target}” is not in the knowledge base.`,
      mdChain: 'Chain',
      mdHead: '| Query | Arrows followed | Verdict |',
      mdEnd: (n) => `${n}, chain ended`,
      mdYes: 'Yes',
      mdUnknown: 'Unknown',
    },
    expert: {
      facts: 'FACTS · SCENARIO A',
      if: 'IF',
      then: 'THEN',
      chain: 'chain',
      advice: 'SYSTEM ADVICE',
      three: 'THREE SCENARIOS',
      cols: ['Scenario', 'Facts on', 'Fired', 'Advice line'],
      short: { yagmur: 'Rain', soguk: 'Cold', ruzgar: 'Wind' },
      scen: ['A (initial)', 'B', 'C'],
      mdHead: '| Scenario | Facts on | Rules fired | Advice line |',
      mdNote: '> Emojis in the rule and advice texts were dropped in the printed figure.',
    },
    grid: {
      bfs: 'UNINFORMED (BFS)',
      greedy: 'INFORMED (GREEDY)',
      start: 'S',
      goal: 'G',
      explored: (n) => `Explored: ${n}`,
      pathLen: (cells, steps) => `Path length: ${cells} cells (${steps} steps)`,
      legend: { visited: 'explored', path: 'path found', wall: 'wall' },
      legendSG: 'S start · G goal',
      note: 'Cell number: exploration order (1 = S). Column/row numbers start at 1.',
      mdGrid: 'Grid 8×6, S=(1,1), G=(8,6); walls (column,row): ',
      mdHead: '| Method | Cells explored | Path (cells) | Steps |',
      mdBfs: 'Uninformed (BFS)',
      mdGreedy: 'Informed (greedy)',
      mdOrderBfs: 'BFS exploration order',
      mdOrderGreedy: 'Greedy exploration order',
      mdPath: 'Path',
    },
    markov: {
      matrix: 'Transition matrix (%)',
      today: 'today',
      tomorrow: 'tomorrow',
    },
  },
};
