// Bölüm 5 figür etiketleri ve veri dizileri (tr / en).
// TR: gen/M05.mjs'nin önceki sabitleriyle birebir. EN: Atlas-Kitap-EN.dc.html renderVals() (token 2153–2171, embed 2172–2194,
// attn 2195–2217, generate 2218–2244, train 2245–2257, diffuse 2258–2280, ctx 2281–2298) ve şablonlar 580–684; figüre özel
// etiketler (KARE, SONUÇ, AĞIRLIK…) burada İngilizceleştirildi. Sayısal veriler (koordinat, olasılık, tohum) gen/ içinde kalır.
export default {
  tr: {
    token: {
      examples: ['Merhaba dünya, bugün 2026.', 'Yapay zekâ metni token’lara böler.', 'Tokenleştirme şaşırtıcı derecede önemli!'],
      sentence: (n) => `CÜMLE ${n}`,
      count: (words) => ` token · ${words} kelime`,
      legend: '“##” = önceki parçanın devamı (bir kelime bölündüğünde kullanılır)',
      mdTitle: (title) => `# Token tablosu — ${title}`,
      mdHead: '| Cümle | Token’lar | Kelime | Token |',
    },
    embed: {
      words: ['kedi', 'köpek', 'kuş', 'kral', 'kraliçe', 'prens', 'elma', 'ekmek', 'peynir'],
      family: { animal: 'hayvan', royalty: 'krallık', food: 'yiyecek' },
      selected: (w, list) => `“${w}” seçili · en yakın 2 komşu: ${list}`,
      neighbor: (w, d) => `“${w}” (${d})`,
      sameFamily: (f) => `ikisi de “${f}” ailesinden · yakınlık, benzer anlam demek`,
      distance: (a, b, dx, dy, d) => `uzaklık = √(Δx² + Δy²) · ${a}–${b}: √(${dx}² + ${dy}²) = ${d}`,
      mdTitle: (title) => `# Koordinat tablosu — ${title}`,
      mdHead: '| Kelime | Aile | x | y | En yakın 2 komşu (uzaklık) |',
      mdNote: '> Ekrandaki üç renk (kırmızı/mavi/yeşil) baskıda kesikli aile daireleri ve aile adıyla verildi.',
    },
    attn: {
      tokens: ['Kedi', 'kaçtı', 'çünkü', 'o', 'korkmuştu'],
      query: 'sorgu ↓',
      key: 'bakılan →',
      weight: 'AĞIRLIK',
      // R038: en koyu hücre kendisiyse "kendi konumu" + "diğerleri arasında en çok …"; değilse kendi payı da yazılır. Gönderge iddiası yok.
      caption: (q, v, best, selfV, other, otherV) => (best === q
        ? `“${q}” sorgu: en koyu hücre kendi konumu (${v}) · diğerleri arasında en çok “${other}” (${otherV})`
        : `“${q}” sorgu: en koyu hücre ${v} ile “${best}” · kendi konumu ${selfV}`),
      note: ['temsili, çift yönlü (encoder) tablo · ağırlıklar elle seçildi', 'tek bir dikkat hücresi göndergenin çözüldüğünü kanıtlamaz'],
      legend: 'kalın = satırın en yükseği · Σ = satır toplamı (her satır 1.00)',
      mdTitle: (title) => `# Dikkat ağırlıkları — ${title}`,
      mdHead: 'Sorgu ↓ · Bakılan →',
    },
    generate: {
      steps: [['çok', 'artık', 'bugün', 'giderek'], ['hızlı', 'güçlü', 'yaygın', 'akıllı'], ['gelişiyor', 'ilerliyor', 'yayılıyor', 'büyüyor']],
      prefix: 'Yapay zekâ ',
      // R040: iki satır — açgözlü (argmax) ve T = 1.5 örneklemesi (demo-data.json temp54 kuralı)
      greedy: 'AÇGÖZLÜ (ARGMAX) · HER ADIMDA EN YÜKSEK OLASILIK',
      sample: (T) => `ÖRNEKLEME, T = ${T} · softmax(z/T) · SEÇİM: U İLE TERS-CDF`,
      step: (n) => `ADIM ${n}`,
      result: 'SONUÇ',
      chosen: (list) => `seçilen: ${list}`,
      footer: (T, us) => `z = ln p · örnekleme: softmax(z/${T}), yuvarlanmış · U = ${us}`,
      mdTitle: (title) => `# Aday tablosu — ${title}`,
      mdRule: (T) => `Kural (demo-data.json temp54): açgözlü satır her adımda argmax; örnekleme satırında z = ln p, q = softmax(z/${T}), seçim U ile ters-CDF (adım i → U[i mod 8], ilk u < kümülatif q).`,
      mdHead: (T) => `| Adım | Adaylar ve olasılıklar p | Açgözlü seçim | softmax(z/${T}) | U → örnekleme seçimi |`,
      mdLow: (s) => `Açgözlü (argmax): ${s}`,
      mdHigh: (s, T) => `Örnekleme, T = ${T}: ${s}`,
    },
    train: {
      stages: [
        { name: '1 · Ön eğitim', data: 'Devasa internet metni', learns: 'Dili ve dünyayı (bir sonraki kelimeyi tahmin)', out: 'Türkiye’nin başkenti Ankara’dır ve nüfusu yaklaşık altı milyondur. Bu şehir...', note: 'Ham model “tamamlayıcı”dır: soruyu cevaplamaz, metni sürdürür.' },
        { name: '2 · İnce ayar', data: 'Talimat–cevap çiftleri', learns: 'Yönergeyi izlemeyi (soruyu cevaplamayı)', out: 'Türkiye’nin başkenti Ankara’dır.', note: 'Artık soruyu doğrudan, derli toplu cevaplıyor.' },
        { name: '3 · RLHF / hizalama', data: 'İnsan tercihleri (tercih çiftleri)', learns: 'Yardımcı, dürüst ve güvenli olmayı', out: 'Türkiye’nin başkenti Ankara’dır. İstersen şehir hakkında birkaç ilginç bilgi de paylaşabilirim. 🙂', note: 'Aynı bilgi; ama daha yardımcı, kibar ve hizalı bir tonla.' },
      ],
      rowData: ['VERİ'],
      rowLearns: ['ÖĞRENDİĞİ'],
      rowOut: ['ÇIKTI', '“Türkiye’nin', 'başkenti?”', 'sorusuna'],
      rowNote: ['NOT'],
      flow: 'aynı soru, üç aşama: bilgi aynı, sunuş değişiyor',
      mdTitle: (title) => `# Üç aşama — ${title}`,
      mdData: 'Veri',
      mdLearns: 'Öğrendiği',
      mdOut: 'Örnek çıktı (“Türkiye’nin başkenti?”)',
      mdNote: 'Not',
      mdEmoji: (kept) => `> Figürde 3. aşamanın 🙂 emojisi ${kept ? 'korundu' : 'çıkarıldı'} (duotone baskı); KEEP_EMOJI sabitiyle değişir.`,
    },
    diffuse: {
      reverse: 'TERS SÜREÇ (ÜRETİM): GÜRÜLTÜDEN ŞEKLE',
      forward: 'İLERİ SÜREÇ (EĞİTİM): ŞEKLE GÜRÜLTÜ EKLEME',
      frame: (n) => `KARE ${n}`,
      legHeart: 'kalp pikseli (ekranda mor)',
      legClear: 'açık piksel',
      legNoise: 'gürültü (çözülmemiş)',
      under: 'her karenin altında: ilerleme (adım/8, %) · çözülen piksel / 64 (ayrı nicelik)', // R042
      mdTitle: (title) => `# Adım tablosu — ${title}`,
      mdHead: '| Adım | İlerleme (adım/8) | Çözülen piksel (64’te) | Görünen kalp pikseli |',
      mdFormula: 'rand(i) = frac(sin(i·12.9898 + 78.233)·43758.5453); piksel i, adım s’de rand(i) < s/8 ise çözülür. Kalp 40 piksel.',
    },
    ctx: {
      pool: ['Yapay', 'zekâ', 'modelleri', 'metni', 'sınırlı', 'bir', 'pencerede', 'tutar', 've', 'eskiyi', 'zamanla', 'unutur'],
      title: (max) => `Bağlam penceresi · en fazla ${max} kelime`,
      legend: 'koyu çerçeve = pencerede · soluk = unutuldu',
      frame: (k, n) => `KARE ${k} · ${n}. KELİME`,
      empty: 'pencere boş',
      full: (used, max, forgotten) => `pencere dolu ${used}/${max} · unutulan ${forgotten}`,
      justFull: (used, max) => `pencere tam doldu ${used}/${max}`,
      partial: (used, max) => `pencere ${used}/${max}`,
      emptyChip: '(boş)',
      line: (max) => `turuncu çizgi = modelin gördüğü pencere (son ${max} kelime)`,
      mdTitle: (title) => `# Pencere tablosu — ${title}`,
      mdSentence: (s, max) => `Cümle: “${s}.” · pencere = ${max} kelime`,
      mdHead: '| Eklenen kelime | Pencerede olanlar | Unutulanlar |',
    },
  },
  en: {
    token: {
      examples: ['Hello world, today is 2026.', 'Artificial intelligence splits text into tokens.', 'Tokenization is surprisingly important!'],
      sentence: (n) => `SENTENCE ${n}`,
      count: (words) => ` tokens · ${words} words`,
      legend: '“##” = continuation of the previous piece (used when a word is split)',
      mdTitle: (title) => `# Token table — ${title}`,
      mdHead: '| Sentence | Tokens | Words | Tokens |',
    },
    embed: {
      words: ['cat', 'dog', 'bird', 'king', 'queen', 'prince', 'apple', 'bread', 'cheese'],
      family: { animal: 'animal', royalty: 'royalty', food: 'food' },
      selected: (w, list) => `“${w}” selected · 2 nearest neighbors: ${list}`,
      neighbor: (w, d) => `“${w}” (${d})`,
      sameFamily: (f) => `both from the “${f}” family · closeness means similar meaning`,
      distance: (a, b, dx, dy, d) => `distance = √(Δx² + Δy²) · ${a}–${b}: √(${dx}² + ${dy}²) = ${d}`,
      mdTitle: (title) => `# Coordinate table — ${title}`,
      mdHead: '| Word | Family | x | y | 2 nearest neighbors (distance) |',
      mdNote: '> The three on-screen colors (red/blue/green) are rendered in print as dashed family circles with the family name.',
    },
    attn: {
      tokens: ['The cat', 'ran', 'because', 'it', 'was scared'],
      query: 'query ↓',
      key: 'attends to →',
      weight: 'WEIGHT',
      caption: (q, v, best, selfV, other, otherV) => (best === q
        ? `“${q}” query: darkest cell is its own (${v}) · among the others, most at “${other}” (${otherV})`
        : `“${q}” query: darkest cell ${v} at “${best}” · its own cell ${selfV}`),
      note: ['illustrative, bidirectional (encoder-style) table · weights chosen by hand', 'a single attention cell does not prove the reference is resolved'],
      legend: 'bold = row maximum · Σ = row sum (each row 1.00)',
      mdTitle: (title) => `# Attention weights — ${title}`,
      mdHead: 'Query ↓ · Attends to →',
    },
    generate: {
      steps: [['now', 'already', 'today', 'rapidly'], ['learns', 'writes', 'creates', 'reasons'], ['fast', 'well', 'daily', 'deeply']],
      prefix: 'AI ',
      greedy: 'GREEDY (ARGMAX) · HIGHEST PROBABILITY AT EVERY STEP',
      sample: (T) => `SAMPLING, T = ${T} · softmax(z/T) · PICK: INVERSE CDF WITH U`,
      step: (n) => `STEP ${n}`,
      result: 'RESULT',
      chosen: (list) => `chosen: ${list}`,
      footer: (T, us) => `z = ln p · sampling row: softmax(z/${T}), rounded · U = ${us}`,
      mdTitle: (title) => `# Candidate table — ${title}`,
      mdRule: (T) => `Rule (demo-data.json temp54): the greedy row takes the argmax at every step; in the sampling row z = ln p, q = softmax(z/${T}), the pick uses inverse CDF with U (step i → U[i mod 8], first u < cumulative q).`,
      mdHead: (T) => `| Step | Candidates and probabilities p | Greedy pick | softmax(z/${T}) | U → sampled pick |`,
      mdLow: (s) => `Greedy (argmax): ${s}`,
      mdHigh: (s, T) => `Sampling, T = ${T}: ${s}`,
    },
    train: {
      stages: [
        { name: '1 · Pretraining', data: 'Massive internet text', learns: 'Language and the world (next-word prediction)', out: 'The capital of Türkiye is Ankara, with a population of about six million. The city...', note: 'The raw model is a “completer”: it doesn’t answer the question, it continues the text.' },
        { name: '2 · Fine-tuning', data: 'Instruction–response pairs', learns: 'Following instructions (answering the question)', out: 'The capital of Türkiye is Ankara.', note: 'Now it answers directly and concisely.' },
        { name: '3 · RLHF / alignment', data: 'Human preferences (preference pairs)', learns: 'Being helpful, honest and safe', out: 'The capital of Türkiye is Ankara. If you’d like, I can also share a few interesting facts about the city. 🙂', note: 'Same fact; a more helpful, polite, aligned tone.' },
      ],
      rowData: ['DATA'],
      rowLearns: ['LEARNS'],
      rowOut: ['OUTPUT', 'for “capital', 'of Türkiye?”'],
      rowNote: ['NOTE'],
      flow: 'same question, three stages: same fact, different delivery',
      mdTitle: (title) => `# Three stages — ${title}`,
      mdData: 'Data',
      mdLearns: 'What it learns',
      mdOut: 'Sample output (“capital of Türkiye?”)',
      mdNote: 'Note',
      mdEmoji: (kept) => `> In the figure the 🙂 emoji of stage 3 is ${kept ? 'kept' : 'removed'} (duotone print); set by the KEEP_EMOJI constant.`,
    },
    diffuse: {
      reverse: 'REVERSE PROCESS (GENERATION): NOISE TO SHAPE',
      forward: 'FORWARD PROCESS (TRAINING): ADDING NOISE TO THE SHAPE',
      frame: (n) => `FRAME ${n}`,
      legHeart: 'heart pixel (purple on screen)',
      legClear: 'clear pixel',
      legNoise: 'noise (unresolved)',
      under: 'under each frame: progress (step/8, %) · resolved pixels / 64 (a different quantity)', // R042
      mdTitle: (title) => `# Step table — ${title}`,
      mdHead: '| Step | Progress (step/8) | Resolved pixels (of 64) | Visible heart pixels |',
      mdFormula: 'rand(i) = frac(sin(i·12.9898 + 78.233)·43758.5453); pixel i is resolved at step s if rand(i) < s/8. The heart has 40 pixels.',
    },
    ctx: {
      pool: ['Language', 'models', 'hold', 'text', 'inside', 'a', 'limited', 'window', 'and', 'forget', 'older', 'words'],
      title: (max) => `Context window · at most ${max} words`,
      legend: 'dark border = in the window · faded = forgotten',
      frame: (k, n) => `FRAME ${k} · WORD ${n}`,
      empty: 'window empty',
      full: (used, max, forgotten) => `window full ${used}/${max} · forgotten ${forgotten}`,
      justFull: (used, max) => `window just filled ${used}/${max}`,
      partial: (used, max) => `window ${used}/${max}`,
      emptyChip: '(empty)',
      line: (max) => `orange line = the window the model sees (last ${max} words)`,
      mdTitle: (title) => `# Window table — ${title}`,
      mdSentence: (s, max) => `Sentence: “${s}.” · window = ${max} words`,
      mdHead: '| Word added | In the window | Forgotten |',
    },
  },
};
