// Bölüm 6 figür etiketleri ve verileri (tr / en).
// TR: gen/M06.mjs'deki metinlerin birebir aynısı. EN: Atlas-Kitap-EN.dc.html renderVals() (prompt/rag/agent/arch/sector)
// ve şablon etiketleri; figüre özgü etiketler (KARE, ÜÇ KOL, eşik notu vb.) burada İngilizceleştirildi.
export default {
  tr: {
    prompt: {
      base: 'Bana bir hafta sonu tatil planı öner.',
      parts: [
        { name: 'Rol', text: 'Sen deneyimli bir seyahat danışmanısın.' },
        { name: 'Bağlam', text: '3 kişilik bir aile, deniz kenarında, orta bütçeli bir tatil istiyor.' },
        { name: 'Örnek', text: 'Örnek: “Gün 1 · Sabah: …, Öğlen: …, Akşam: …”' },
        { name: 'Format', text: 'Cevabı gün başlıklarıyla, madde madde ver.' },
      ],
      resp: {
        low: 'Bir yere gidebilirsiniz, birkaç müze gezip güzel yemekler yiyebilirsiniz. İyi tatiller!',
        mid: 'Deniz kenarında bir destinasyon öneriyorum: sabah plaj, öğleden sonra kısa bir kasaba turu, akşam balık restoranı. Bütçeye uygun bir pansiyon seçebilirsiniz.',
        high: 'Gün 1 · Sabah: plajda yüzme; Öğlen: sahilde hafif öğle; Akşam: yerel balıkçıda akşam yemeği.\nGün 2 · Sabah: kasaba & pazar turu; Öğlen: aile dostu kafe; Akşam: gün batımı yürüyüşü.',
      },
      tier: { high: 'yüksek', mid: 'orta', low: 'düşük' },
      tierBox: { low: 'DÜŞÜK · %40–55 (n = 0, 1)', mid: 'ORTA · %70 (n = 2)', high: 'YÜKSEK · %85–100 (n = 3, 4)' },
      stackTitle: 'İSTEM: TABAN + DÖRT PARÇA',
      baseName: 'Taban istek',
      partTag: (n) => `+ parça ${n}`,
      ladderTitle: 'KALİTE = 40 + 15·n',
      baseOnly: 'yalnız taban',
      addPart: (name) => `+ ${name.toLowerCase()}`,
      note: 'Eşikler: 60 altı düşük, 60–84 orta, 85 ve üstü yüksek. Kural parçanın hangisi olduğuna bakmaz, yalnız sayısına (n) bakar.',
      answersTitle: 'MODELİN CEVABI (GÖSTERİM) · DÜZEYE GÖRE',
      md: {
        title: 'İstem parçaları',
        partsHead: '| Parça | İsteme eklenen cümle |',
        stepsHead: '| n (eklenen parça) | Kalite | Düzey | Cevap |',
        rule: 'kalite = min(100, 40 + 15·n); düzey: ≥85 yüksek, 60–84 orta, <60 düşük.',
      },
    },
    rag: {
      docs: [
        { q: 'Yıllık izin hakkım kaç gün?', chunk: 'İK Politikası §4: Tam zamanlı çalışanlara yılda 20 gün ücretli yıllık izin verilir; 5 yıldan sonra 26 güne çıkar.', ungrounded: 'Genelde yıllık izin 14 gün civarındadır ama şirketinize göre değişebilir.', grounded: 'İK Politikası §4’e göre tam zamanlı çalışanlar yılda 20 gün ücretli izin alır (5 yıldan sonra 26 gün).' },
        { q: 'Uzaktan çalışma kuralı nedir?', chunk: 'İK Politikası §7: Çalışanlar haftada en fazla 3 gün uzaktan çalışabilir; Salı günleri ofiste olunması beklenir.', ungrounded: 'Çoğu şirkette haftada 2 gün uzaktan çalışmaya izin verilir sanırım.', grounded: 'İK Politikası §7’ye göre haftada en fazla 3 gün uzaktan çalışılabilir; Salı günü ofiste olunması beklenir.' },
        { q: 'Yemek harcama limiti ne kadar?', chunk: 'Harcama Yönergesi §2: İş yemeklerinde kişi başı günlük limit 500 TL’dir; fatura ibrazı zorunludur.', ungrounded: 'Limit muhtemelen 250–300 TL arasıdır, emin değilim.', grounded: 'Harcama Yönergesi §2’ye göre iş yemeklerinde kişi başı günlük limit 500 TL’dir ve fatura gerekir.' },
      ],
      nodes: ['Soru', 'Getirme', 'Kaynak parçası', 'Model', 'Cevap'],
      flowOn: 'RAG AÇIK: SORU → GETİRME → KAYNAK PARÇASI → MODEL → CEVAP',
      flowOff: 'RAG KAPALI: getirme yok, model ezberinden tahmin eder',
      question: (n) => `SORU ${n}`,
      offHead: 'RAG KAPALI · KAYNAKSIZ TAHMİN',
      onHead: 'RAG AÇIK · KAYNAKLI CEVAP',
      noSource: 'kaynak yok: belgeye bakılmadı',
      retrieved: 'GETİRİLEN KAYNAK',
      unverified: '⚠ Doğrulanmadı: yanlış olabilir.',
      source: (s) => `Kaynak: ${s}`,
      md: {
        title: 'Üç soru, iki durum',
        head: '| Soru | Bulunan kaynak parçası (RAG açık) | RAG kapalı: kaynaksız tahmin | RAG açık: kaynaklı cevap |',
      },
    },
    agent: {
      task: 'Ekibe 3 pizza alacağız (tanesi 180 TL). Toplam ne kadar ve 6 kişiye bölünce kişi başı ne düşer?',
      steps: [
        { thought: 'Önce toplam tutarı bulmalıyım: 3 × 180.', tool: 'hesap makinesi', action: 'hesap_makinesi("3 * 180")', obs: '540', isFinal: false },
        { thought: 'Şimdi kişi başını bulayım: 540 ÷ 6.', tool: 'hesap makinesi', action: 'hesap_makinesi("540 / 6")', obs: '90', isFinal: false },
        { thought: 'Yeterli bilgim var, cevabı yazabilirim.', tool: null, action: null, obs: null, isFinal: true, final: 'Toplam 540 TL; 6 kişiye bölününce kişi başı 90 TL.' },
      ],
      taskHead: 'GÖREV',
      singleTool: 'Tek araç: hesap makinesi',
      loopTitle: 'REACT DÖNGÜSÜ',
      nodeThought: 'Düşünce',
      nodeTool: 'Araç',
      nodeObs: 'Gözlem',
      goal: 'hedefe ulaşınca: son cevap',
      edgeCall: 'çağrı',
      edgeOut: 'çıktı',
      edgeFeed: 'besler',
      frame: (n) => `KARE ${n}`,
      thoughtHead: 'DÜŞÜNCE',
      toolHead: 'ARAÇ',
      toolLine: (t) => `araç: ${t}`,
      obsHead: 'GÖZLEM',
      noTool: '· (araç çağrısı yok)',
      finalHead: '✓ SON CEVAP',
      md: {
        title: 'Adım tablosu',
        task: (s) => `Görev: ${s}`,
        head: '| Adım | Düşünce | Araç çağrısı | Gözlem |',
        noTool: '(araç yok)',
        final: (s) => `Son cevap: ${s}`,
      },
    },
    arch: {
      parts: [
        { name: 'Arayüz', desc: 'Kullanıcının soruyu yazdığı, cevabı gördüğü yer (sohbet ekranı, uygulama).' },
        { name: 'Orkestrasyon', desc: 'Asıl “beyin”: istemi hazırlar, hangi aracı/bilgiyi ne zaman çağıracağına karar verir, akışı yönetir.' },
        { name: 'Bilgi tabanı', desc: 'Senin verin (belgeler, notlar) burada gömü olarak durur; RAG ile ilgili parça getirilir.' },
        { name: 'Araçlar', desc: 'Modelin dünyayla etkileşimi: hesap, arama, takvim, e-posta, bir API ya da kod çalıştırma.' },
        { name: 'Bellek', desc: 'Konuşmanın geçmişini ve kullanıcıya dair durumu tutar; bağlamın sürmesini sağlar.' },
      ],
      flowTitle: 'AKIŞ: KULLANICI → ARAYÜZ → ORKESTRASYON → ÜÇ KOL',
      user: 'Kullanıcı',
      brain: 'asıl “beyin”',
      modelCall: 'model çağrısı',
      ragTag: '(RAG)',
      modelNote: 'Model ayrı kutu değil; orkestrasyon onu çağırır.',
      colPart: 'PARÇA',
      colRole: 'SİSTEMDEKİ ROLÜ',
      md: {
        title: 'Parçalar ve rolleri',
        head: '| # | Parça | Sistemdeki rolü |',
        flow: 'Akış: Kullanıcı ↔ Arayüz ↔ Orkestrasyon ↔ {Bilgi tabanı, Araçlar, Bellek}. Model ayrı kutu değil; orkestrasyonun içinden çağrılır.',
      },
    },
    sector: {
      list: [
        { name: 'Sağlık', ex: ['Tıbbi görüntülerde (röntgen, MR) anormallik tespiti', 'Hasta notlarını özetleme ve kodlama', 'İlaç keşfinde aday molekül tarama'] },
        { name: 'Finans', ex: ['Gerçek zamanlı dolandırıcılık tespiti', 'Belge/sözleşme analizi ve risk skorlama', 'Müşteri destek asistanları'] },
        { name: 'Üretim', ex: ['Kestirimci bakım (arızayı önceden görme)', 'Görüntüyle kalite kontrol', 'Tedarik/talep tahmini'] },
        { name: 'Bilim', ex: ['Protein katlanması ve yapı tahmini', 'Büyük veri kümelerinde örüntü keşfi', 'Simülasyon ve hipotez üretimi'] },
        { name: 'Sanat', ex: ['Görsel, müzik ve metin üretimi', 'Konsept tasarım ve eskiz hızlandırma', 'Üslup aktarımı ve restorasyon'] },
        { name: 'Günlük', ex: ['Çeviri ve yazma yardımı', 'Öneri sistemleri (film, ürün)', 'Sesli asistanlar ve özetleme'] },
      ],
      md: {
        title: 'Altı alan, on sekiz örnek',
        head: '| Alan | Örnek 1 | Örnek 2 | Örnek 3 |',
      },
    },
  },

  en: {
    prompt: {
      base: 'Suggest a weekend trip plan for me.',
      parts: [
        { name: 'Role', text: 'You are an experienced travel advisor.' },
        { name: 'Context', text: 'A family of three wants a mid-budget beach trip.' },
        { name: 'Example', text: 'Example: “Day 1 · Morning: ..., Noon: ..., Evening: ...”' },
        { name: 'Format', text: 'Answer with day headers, as bullet points.' },
      ],
      resp: {
        low: 'You could go somewhere, see a few museums and eat nice food. Have a great trip!',
        mid: 'I suggest a beach destination: swimming in the morning, a short town tour in the afternoon, a fish restaurant in the evening. A budget-friendly guesthouse would fit.',
        high: 'Day 1 · Morning: swim at the beach; Noon: light lunch by the shore; Evening: dinner at the local fish place.\nDay 2 · Morning: town & market tour; Noon: family-friendly café; Evening: sunset walk.',
      },
      tier: { high: 'high', mid: 'medium', low: 'low' },
      tierBox: { low: 'LOW · 40–55% (n = 0, 1)', mid: 'MEDIUM · 70% (n = 2)', high: 'HIGH · 85–100% (n = 3, 4)' },
      stackTitle: 'PROMPT: BASE + FOUR PIECES',
      baseName: 'Base request',
      partTag: (n) => `+ piece ${n}`,
      ladderTitle: 'QUALITY = 40 + 15·n',
      baseOnly: 'base only',
      addPart: (name) => `+ ${name.toLowerCase()}`,
      note: 'Thresholds: below 60 low, 60–84 medium, 85 and above high. The rule ignores which piece was added; it only counts them (n).',
      answersTitle: 'MODEL’S ANSWER (ILLUSTRATIVE) · BY TIER',
      md: {
        title: 'Prompt pieces',
        partsHead: '| Piece | Sentence added to the prompt |',
        stepsHead: '| n (pieces added) | Quality | Tier | Answer |',
        rule: 'quality = min(100, 40 + 15·n); tier: ≥85 high, 60–84 medium, <60 low.',
      },
    },
    rag: {
      docs: [
        { q: 'How many days of annual leave do I get?', chunk: 'HR Policy §4: Full-time employees receive 20 days of paid annual leave per year, rising to 26 after 5 years.', ungrounded: 'Annual leave is usually around 14 days, but it varies by company.', grounded: 'Per HR Policy §4, full-time employees get 20 paid days a year (26 after 5 years).' },
        { q: 'What is the remote-work rule?', chunk: 'HR Policy §7: Employees may work remotely up to 3 days a week; Tuesdays are office days.', ungrounded: 'Most companies allow about 2 remote days a week, I think.', grounded: 'Per HR Policy §7, up to 3 remote days a week are allowed; Tuesdays are office days.' },
        { q: 'What is the meal expense limit?', chunk: 'Expense Guide §2: The per-person daily limit for business meals is 500 TL; a receipt is required.', ungrounded: 'The limit is probably around 250–300 TL, I’m not sure.', grounded: 'Per Expense Guide §2, the per-person daily limit for business meals is 500 TL, and a receipt is required.' },
      ],
      nodes: ['Question', 'Retrieval', 'Source chunk', 'Model', 'Answer'],
      flowOn: 'RAG ON: QUESTION → RETRIEVAL → SOURCE CHUNK → MODEL → ANSWER',
      flowOff: 'RAG OFF: no retrieval, the model guesses from memory',
      question: (n) => `QUESTION ${n}`,
      offHead: 'RAG OFF · UNSOURCED GUESS',
      onHead: 'RAG ON · SOURCED ANSWER',
      noSource: 'no source: document not consulted',
      retrieved: 'RETRIEVED SOURCE',
      unverified: '⚠ Unverified; it may sound right but be wrong.',
      source: (s) => `Source: ${s}`,
      md: {
        title: 'Three questions, two modes',
        head: '| Question | Retrieved source chunk (RAG on) | RAG off: unsourced guess | RAG on: sourced answer |',
      },
    },
    agent: {
      task: 'We’re buying 3 pizzas for the team (180 TL each). What’s the total, and the per-person share among 6?',
      steps: [
        { thought: 'First I need the total: 3 × 180.', tool: 'Calculator', action: 'calculator("3 * 180")', obs: '540', isFinal: false },
        { thought: 'Now the per-person share: 540 ÷ 6.', tool: 'Calculator', action: 'calculator("540 / 6")', obs: '90', isFinal: false },
        { thought: 'I have enough information; I can write the answer.', tool: null, action: null, obs: null, isFinal: true, final: 'The total is 540 TL; split among 6, that’s 90 TL per person.' },
      ],
      taskHead: 'TASK',
      singleTool: 'Single tool: calculator',
      loopTitle: 'REACT LOOP',
      nodeThought: 'Thought',
      nodeTool: 'Tool',
      nodeObs: 'Observation',
      goal: 'goal reached: final answer',
      edgeCall: 'call',
      edgeOut: 'output',
      edgeFeed: 'feeds',
      frame: (n) => `FRAME ${n}`,
      thoughtHead: 'THOUGHT',
      toolHead: 'TOOL',
      toolLine: (t) => `tool: ${t}`,
      obsHead: 'OBSERVATION',
      noTool: '· (no tool call)',
      finalHead: '✓ FINAL ANSWER',
      md: {
        title: 'Step table',
        task: (s) => `Task: ${s}`,
        head: '| Step | Thought | Tool call | Observation |',
        noTool: '(no tool)',
        final: (s) => `Final answer: ${s}`,
      },
    },
    arch: {
      parts: [
        { name: 'Interface', desc: 'Where the user types the question and sees the answer (chat screen, app).' },
        { name: 'Orchestration', desc: 'The real “brain”: builds the prompt, decides which tool or knowledge to call and when, manages the flow.' },
        { name: 'Knowledge base', desc: 'Your data (documents, notes) lives here as embeddings; RAG retrieves the relevant chunk.' },
        { name: 'Tools', desc: 'The model’s link to the world: calculation, search, calendar, email, an API or running code.' },
        { name: 'Memory', desc: 'Holds the conversation history and user state; keeps the context going.' },
      ],
      flowTitle: 'FLOW: USER → INTERFACE → ORCHESTRATION → THREE ARMS',
      user: 'User',
      brain: 'the real “brain”',
      modelCall: 'model call',
      ragTag: '(RAG)',
      modelNote: 'The model is not a separate box; orchestration calls it.',
      colPart: 'PART',
      colRole: 'ROLE IN THE SYSTEM',
      md: {
        title: 'Parts and their roles',
        head: '| # | Part | Role in the system |',
        flow: 'Flow: User ↔ Interface ↔ Orchestration ↔ {Knowledge base, Tools, Memory}. The model is not a separate box; it is called from inside orchestration.',
      },
    },
    sector: {
      list: [
        { name: 'Health', ex: ['Spotting anomalies in medical images (X-ray, MRI)', 'Summarizing and coding patient notes', 'Screening candidate molecules in drug discovery'] },
        { name: 'Finance', ex: ['Real-time fraud detection', 'Document/contract analysis and risk scoring', 'Customer support assistants'] },
        { name: 'Manufacturing', ex: ['Predictive maintenance (foreseeing failures)', 'Visual quality control', 'Supply/demand forecasting'] },
        { name: 'Science', ex: ['Protein folding and structure prediction', 'Pattern discovery in large datasets', 'Simulation and hypothesis generation'] },
        { name: 'Art', ex: ['Image, music and text generation', 'Concept design and faster sketching', 'Style transfer and restoration'] },
        { name: 'Daily life', ex: ['Translation and writing help', 'Recommendation systems (movies, products)', 'Voice assistants and summarization'] },
      ],
      md: {
        title: 'Six fields, eighteen examples',
        head: '| Field | Example 1 | Example 2 | Example 3 |',
      },
    },
  },
};
