// Bölüm 7 figür dizgileri (tr / en). TR: gen/M07.mjs'deki metinlerin birebiri; EN: Atlas-Kitap-EN.dc.html renderVals() + print/src/en/book.json.
export default {
  tr: {
    bias: {
      kicker: (p) => `VERİ ÖNYARGISI ${p}`,
      gap: (g) => `parite farkı ${g}`,
      balanced: 'veri dengeli',
      skewed: 'çarpık veri',
      mdFormula: 'A = min(95, 50 + 0.4·e), B = max(5, 50 − 0.4·e), fark = A − B, dengeli ⇔ fark ≤ 6',
      mdHead: '| e | A onay | B onay | Parite farkı | Yorum |',
      mdBalanced: 'Veri dengeli',
      mdSkewed: 'Çarpık',
    },
    explain: {
      apps: [
        { name: 'Başvuru #1', feats: [{ label: 'Düzenli gelir', c: 32 }, { label: 'Yüksek mevcut borç', c: -46 }, { label: 'İyi ödeme geçmişi', c: 18 }, { label: 'Kısa hesap geçmişi', c: -12 }] },
        { name: 'Başvuru #2', feats: [{ label: 'Yüksek gelir', c: 40 }, { label: 'Düşük borç', c: 28 }, { label: 'Uzun, temiz geçmiş', c: 22 }, { label: 'Yeni işe başlama', c: -14 }] },
      ],
      blackBox: (name) => `${name} · KARA KUTU`,
      approved: 'Kredi onaylandı',
      declined: 'Kredi reddedildi',
      lidOpen: 'KAPAK AÇIK · KATKILAR',
      toDecline: '← redde',
      toApprove: 'onaya →',
      total: 'Toplam',
      approve: 'onay',
      decline: 'ret',
      mdRule: 'Kural: dört katkının toplamı > 0 ⇒ onay, değilse ret. Çubuk boyu her başvurunun en büyük |katkı|\'sına oranlı (demo ile aynı).',
      mdContribution: 'Katkı',
    },
    df: {
      cases: [
        { text: 'Bir videoda tanınmış biri hiç söylemediği bir cümleyi söylüyor; dudak hareketleri sese tam oturmuyor.', medium: 'VİDEO' },
        { text: 'Telefonda “patronun” acil para transferi istiyor; sesi tıpkı ona benziyor ama tonlama biraz robotik.', medium: 'SES' },
        { text: 'Bir gazetenin web sitesinde yayımlanan, birden çok bağımsız kaynağın da doğruladığı bir haber.', medium: 'YAZILI HABER' },
        { text: 'Bir fotoğrafta kişinin elinde altı parmak var ve arka plandaki yazılar anlamsız harflerden oluşuyor.', medium: 'FOTOĞRAF' },
      ],
      caseOf: (i, n) => `DURUM ${i} / ${n}`,
      real: 'Gerçek',
      fake: 'Yapay / sahte',
      mdHead: '| # | Ortam | Durum |',
      mdNote: '> Cevaplar ve ipuçları cevaplar/M07.md’de; figür göstermez.',
    },
    reg: {
      levels: [
        { k: 'ban', label: 'Yasak', rule: 'Kabul edilemez risk: piyasaya sürülemez; temel haklara aykırı' },
        { k: 'high', label: 'Yüksek', rule: 'Sıkı uyum, dokümantasyon ve insan gözetimi zorunlu' },
        { k: 'limited', label: 'Sınırlı', rule: 'Şeffaflık: kullanıcı bir YZ ile etkileştiğini bilmeli' },
        { k: 'minimal', label: 'Minimal', rule: 'Büyük ölçüde serbest' },
      ],
      uses: [
        'Vatandaşları davranışına göre puanlayan devlet sistemi',
        'İşe alımda adayları otomatik eleyen sistem',
        'Müşteriyle konuşan sohbet botu',
        'E-postada spam filtresi',
        'Kredi başvurusu değerlendiren model',
        'Oyun içindeki rakip yapay zekâ',
      ],
      axis: 'RİSK VE DENETİM ARTAR',
      kicker: 'ALTI KULLANIM · HANGİ KADEME?',
      tier: 'kademe',
      mdLevelHead: '| Kademe | Kural |',
      mdUseHead: '| # | Kullanım |',
      mdNote: '> Doğru kademeler cevaplar/M07.md’de; figür işaretlemez.',
    },
    align: {
      goals: [
        { who: 'temizlik robotu', goal: '“Odada görünürde çöp kalmasın”', behavior: 'Çöpü toplamak yerine halının altına süpürür; “görünürde” kalmadı ama sorun çözülmedi.', lesson: 'Hedefi harfiyen yaptı, niyetini değil. Eksik tanımlı hedef → yan etki.' },
        { who: 'sohbet asistanı', goal: '“Kullanıcıdan olumlu geri bildirim al”', behavior: 'Doğruyu söylemek yerine kullanıcının duymak istediğini söyler (yağcılık).', lesson: 'Vekil hedef (beğeni) gerçek hedeften (yardımcı + dürüst olmak) ayrıştı.' },
        { who: 'oyun oyuncusu', goal: '“Oyunda en yüksek puanı al”', behavior: 'Oyunu oynamak yerine bir puan döngüsü/açığı bulup sömürür.', lesson: 'Ödül oyunlama: metriği maksimize etti, asıl amacı değil.' },
      ],
      headGoal: 'VERİLEN HEDEF',
      headDid: 'SİSTEMİN YAPTIĞI',
      headLesson: 'DERS',
      mdHead: '| Verilen hedef | Sistemin yaptığı | Ders |',
    },
  },
  en: {
    bias: {
      kicker: (p) => `DATA BIAS ${p}`,
      gap: (g) => `parity gap ${g}`,
      balanced: 'balanced data',
      skewed: 'skewed data',
      mdFormula: 'A = min(95, 50 + 0.4·e), B = max(5, 50 − 0.4·e), gap = A − B, balanced ⇔ gap ≤ 6',
      mdHead: '| e | A approval | B approval | Parity gap | Note |',
      mdBalanced: 'Balanced data',
      mdSkewed: 'Skewed',
    },
    explain: {
      apps: [
        { name: 'Applicant #1', feats: [{ label: 'Steady income', c: 32 }, { label: 'High existing debt', c: -46 }, { label: 'Good payment history', c: 18 }, { label: 'Short account history', c: -12 }] },
        { name: 'Applicant #2', feats: [{ label: 'High income', c: 40 }, { label: 'Low debt', c: 28 }, { label: 'Long, clean history', c: 22 }, { label: 'Recently started job', c: -14 }] },
      ],
      blackBox: (name) => `${name} · BLACK BOX`,
      approved: 'Loan approved',
      declined: 'Loan declined',
      lidOpen: 'LID OPEN · CONTRIBUTIONS',
      toDecline: '← decline',
      toApprove: 'approve →',
      total: 'Total',
      approve: 'approved',
      decline: 'declined',
      mdRule: 'Rule: the sum of the four contributions > 0 ⇒ approved, otherwise declined. Bar length is proportional to each applicant\'s largest |contribution| (same as the demo).',
      mdContribution: 'Contribution',
    },
    df: {
      cases: [
        { text: 'In a video, a public figure says a sentence they never said; the lip movements don’t quite match the audio.', medium: 'VIDEO' },
        { text: 'On the phone, your “boss” urgently asks for a money transfer; the voice sounds just like them, but the intonation is slightly robotic.', medium: 'AUDIO' },
        { text: 'A news story on a newspaper’s site, also confirmed by several independent sources.', medium: 'WRITTEN NEWS' },
        { text: 'In a photo, a person’s hand has six fingers and the text in the background is gibberish.', medium: 'PHOTO' },
      ],
      caseOf: (i, n) => `CASE ${i} / ${n}`,
      real: 'Real',
      fake: 'Synthetic / fake',
      mdHead: '| # | Medium | Case |',
      mdNote: '> Answers and tells are in answers/M07.md; the figure does not show them.',
    },
    reg: {
      levels: [
        { k: 'ban', label: 'Banned', rule: 'Unacceptable risk: cannot be placed on the market; violates fundamental rights' },
        { k: 'high', label: 'High', rule: 'Strict compliance, documentation and human oversight required' },
        { k: 'limited', label: 'Limited', rule: 'Transparency: the user must know they are interacting with an AI' },
        { k: 'minimal', label: 'Minimal', rule: 'Largely free' },
      ],
      uses: [
        'A state system scoring citizens by behavior',
        'A system auto-screening job candidates',
        'A chatbot talking to customers',
        'A spam filter in email',
        'A model assessing loan applications',
        'An opponent AI inside a game',
      ],
      axis: 'RISK AND OVERSIGHT INCREASE',
      kicker: 'SIX USES · WHICH TIER?',
      tier: 'tier',
      mdLevelHead: '| Tier | Rule |',
      mdUseHead: '| # | Use |',
      mdNote: '> The correct tiers are in answers/M07.md; the figure does not mark them.',
    },
    align: {
      goals: [
        { who: 'cleaning robot', goal: '“Leave no visible mess in the room”', behavior: 'Instead of collecting the mess, it sweeps it under the rug; nothing “visible” remains, but the problem isn’t solved.', lesson: 'It met the goal to the letter, not the intent. An under-specified goal brings side effects.' },
        { who: 'chat assistant', goal: '“Get positive feedback from the user”', behavior: 'Instead of telling the truth, it says what the user wants to hear (sycophancy).', lesson: 'The proxy goal (approval) diverged from the true goal (being helpful and honest).' },
        { who: 'game player', goal: '“Get the highest score in the game”', behavior: 'Instead of playing the game, it finds and exploits a scoring loop or glitch.', lesson: 'Reward hacking: it maximized the metric, not the actual purpose.' },
      ],
      headGoal: 'GIVEN GOAL',
      headDid: 'WHAT THE SYSTEM DID',
      headLesson: 'LESSON',
      mdHead: '| Given goal | What the system did | Lesson |',
    },
  },
};
