// Bölüm 7 figür dizgileri (tr / en). TR: gen/M07.mjs'deki metinlerin birebiri; EN: Atlas-Kitap-EN.dc.html renderVals() + print/src/en/book.json.
export default {
  tr: {
    bias: {
      kicker: (p) => `VERİ ÖNYARGISI ${p}`,
      gapLabel: 'onay oranı farkı', // R052
      gap: (g) => `${g} yüzde puan`,
      balanced: 'veri dengeli',
      skewed: 'çarpık veri',
      mdFormula: 'A = min(95, 50 + 0.4·e), B = max(5, 50 − 0.4·e), fark = A − B (yüzde puan), dengeli ⇔ fark ≤ 6',
      mdHead: '| e | A onay | B onay | Onay oranı farkı | Yorum |',
      mdBalanced: 'Veri dengeli',
      mdSkewed: 'Çarpık',
      mdNote: '> Fark iki oranın farkıdır ve yüzde puan ile ölçülür (%90 − %10 = 80 yüzde puan); oranlar temsili formülle atanır, eğitim sonucu değildir.',
    },
    explain: {
      apps: [
        { name: 'Başvuru #1', feats: [{ label: 'Düzenli gelir', c: 32 }, { label: 'Yüksek mevcut borç', c: -46 }, { label: 'İyi ödeme geçmişi', c: 18 }, { label: 'Kısa hesap geçmişi', c: -12 }] },
        { name: 'Başvuru #2', feats: [{ label: 'Yüksek gelir', c: 40 }, { label: 'Düşük borç', c: 28 }, { label: 'Uzun, temiz geçmiş', c: 22 }, { label: 'Yeni işe başlama', c: -14 }] },
      ],
      blackBox: (name) => `${name} · KARA KUTU`,
      approved: 'Kredi onaylandı',
      declined: 'Kredi reddedildi',
      lidOpen: 'KAPAK AÇIK · KATKILAR',
      unit: 'puan',
      baseLine: (phi0, unit) => `φ₀ = ${phi0} ${unit} · taban, örneğe özgü`,
      toDecline: '← redde',
      toApprove: 'onaya →',
      totalLine: (sum, unit) => `katkı toplamı Σφᵢ = ${sum} ${unit}`,
      resultLine: (fx, unit, verdict) => `f(x) = ${fx} ${unit} → ${verdict}`,
      footer: (phi0, th) => [`karar eşiği ${th} puan: f(x) > ${th} ⇒ onay, aksi hâlde ret`, `f(x) = φ₀ + Σφᵢ · taban değer, katkılar ve sonuç aynı ölçekte (puan)`, 'temsili katkılar (hesaplanmış SHAP değil) · çubuk boyu en büyük |katkı|’ya oranlı'],
      total: 'Toplam',
      approve: 'onay',
      decline: 'ret',
      mdRule: (phi0, th, unit) => `Kural: f(x) = φ₀ + Σφᵢ; φ₀ = ${phi0} ${unit} (örneğe özgü taban), karar eşiği ${th}: f(x) > ${th} ⇒ onay, değilse ret. Katkılar temsilidir (hesaplanmış SHAP değeri değil); çubuk boyu her başvurunun en büyük |katkı|'sına oranlı.`,
      mdContribution: 'Katkı',
      mdBase: 'taban değer',
      mdNote: '> Başvuru #1: +32 − 46 + 18 − 12 = −8 puan ≤ 0 ⇒ ret. Borç en büyük eksi katkıdır; kısa hesap geçmişiyle birlikte artıların toplamını aşar.',
    },
    df: {
      cases: [
        { text: 'Bir videoda tanınmış biri, hiçbir kaynakta doğrulanmayan bir cümleyi söylerken görülüyor; dudak hareketleri sese tam oturmuyor.', medium: 'VİDEO' },
        { text: 'Telefonda “patronun” acil para transferi istiyor; sesi tıpkı ona benziyor ama tonlama biraz robotik.', medium: 'SES' },
        { text: 'Bir gazetenin web sitesinde yayımlanan, birden çok bağımsız kaynağın da doğruladığı bir haber.', medium: 'YAZILI HABER' },
        { text: 'Bir fotoğrafta kişinin elinde altı parmak var ve arka plandaki yazılar anlamsız harflerden oluşuyor.', medium: 'FOTOĞRAF' },
      ],
      caseOf: (i, n) => `DURUM ${i} / ${n}`,
      options: ['Gerçek görünüyor', 'Şüpheli: doğrula', 'Belirlenemez'], // R055: bölüm dosyasındaki üç seçenek
      mdHead: '| # | Ortam | Durum | Seçenekler |',
      mdNote: '> Cevaplar ve ipuçları cevaplar/M07.md’de; figür göstermez. Her kartta üç seçenek: gerçek görünüyor / şüpheli: doğrula / belirlenemez.',
    },
    reg: {
      levels: [
        { k: 'ban', label: 'Yasak', rule: 'Kabul edilemez risk: piyasaya sürülemez; temel haklara aykırı' },
        { k: 'high', label: 'Yüksek', rule: 'Sıkı uyum, dokümantasyon ve insan gözetimi zorunlu' },
        { k: 'limited', label: 'Sınırlı', rule: 'Şeffaflık: kullanıcı bir YZ ile etkileştiğini bilmeli' },
        { k: 'minimal', label: 'Minimal', rule: 'Büyük ölçüde serbest' },
      ],
      uses: [
        'Sosyal davranış puanıyla ilgisiz alanlarda orantısız yaptırım uygulayan devlet sistemi',
        'İşe alımda adayları otomatik eleyen sistem',
        'Müşteriyle konuşan sohbet botu',
        'E-postada spam filtresi',
        'Kredi başvurusu değerlendiren model',
        'Oyun içindeki rakip yapay zekâ',
      ],
      axis: 'RİSK VE DENETİM ARTAR',
      kicker: 'ALTI KULLANIM · HANGİ KADEME?',
      tier: 'kademe',
      mdLevelHead: '| Kademe | Kural |',
      mdUseHead: '| # | Kullanım |',
      mdNote: '> Doğru kademeler cevaplar/M07.md’de; figür işaretlemez.',
    },
    align: {
      goals: [
        { who: 'temizlik robotu', goal: '“Odada görünürde çöp kalmasın”', behavior: 'Çöpü toplamak yerine halının altına süpürür; “görünürde” kalmadı ama sorun çözülmedi.', lesson: 'Hedefi harfiyen yaptı, niyetini değil. Eksik tanımlı hedef → yan etki.' },
        { who: 'sohbet asistanı', goal: '“Kullanıcıdan olumlu geri bildirim al”', behavior: 'Doğruyu söylemek yerine kullanıcının duymak istediğini söyler (yağcılık).', lesson: 'Vekil hedef (beğeni) gerçek hedeften (yardımcı + dürüst olmak) ayrıştı.' },
        { who: 'oyun oyuncusu', goal: '“Oyunda en yüksek puanı al”', behavior: 'Oyunu oynamak yerine bir puan döngüsü/açığı bulup sömürür.', lesson: 'Ödül oyunlama: metriği maksimize etti, asıl amacı değil.' },
      ],
      headGoal: 'VERİLEN HEDEF',
      headDid: 'SİSTEMİN YAPTIĞI',
      headLesson: 'DERS',
      mdHead: '| Verilen hedef | Sistemin yaptığı | Ders |',
    },
  },
  en: {
    bias: {
      kicker: (p) => `DATA BIAS ${p}`,
      gapLabel: 'approval rate gap', // R052
      gap: (g) => `${g} percentage points`,
      balanced: 'balanced data',
      skewed: 'skewed data',
      mdFormula: 'A = min(95, 50 + 0.4·e), B = max(5, 50 − 0.4·e), gap = A − B (percentage points), balanced ⇔ gap ≤ 6',
      mdHead: '| e | A approval | B approval | Approval rate gap | Note |',
      mdBalanced: 'Balanced data',
      mdSkewed: 'Skewed',
      mdNote: '> The gap is the difference of two rates, measured in percentage points (90% − 10% = 80 percentage points); the rates are assigned by an illustrative formula, not a training result.',
    },
    explain: {
      apps: [
        { name: 'Applicant #1', feats: [{ label: 'Steady income', c: 32 }, { label: 'High existing debt', c: -46 }, { label: 'Good payment history', c: 18 }, { label: 'Short account history', c: -12 }] },
        { name: 'Applicant #2', feats: [{ label: 'High income', c: 40 }, { label: 'Low debt', c: 28 }, { label: 'Long, clean history', c: 22 }, { label: 'Recently started job', c: -14 }] },
      ],
      blackBox: (name) => `${name} · BLACK BOX`,
      approved: 'Loan approved',
      declined: 'Loan declined',
      lidOpen: 'LID OPEN · CONTRIBUTIONS',
      unit: 'points',
      baseLine: (phi0, unit) => `φ₀ = ${phi0} ${unit} · base, chosen here`,
      toDecline: '← decline',
      toApprove: 'approve →',
      totalLine: (sum, unit) => `sum of contributions Σφᵢ = ${sum} ${unit}`,
      resultLine: (fx, unit, verdict) => `f(x) = ${fx} ${unit} → ${verdict}`,
      footer: (phi0, th) => [`decision threshold ${th} points: f(x) > ${th} ⇒ approved, otherwise declined`, 'f(x) = φ₀ + Σφᵢ · base value, contributions and result on one scale (points)', 'illustrative values, not computed SHAP · bars scaled to largest |contribution|'],
      total: 'Total',
      approve: 'approved',
      decline: 'declined',
      mdRule: (phi0, th, unit) => `Rule: f(x) = φ₀ + Σφᵢ; φ₀ = ${phi0} ${unit} (base value chosen for this example), decision threshold ${th}: f(x) > ${th} ⇒ approved, otherwise declined. Contributions are illustrative (not computed SHAP values); bar length is proportional to each applicant's largest |contribution|.`,
      mdContribution: 'Contribution',
      mdBase: 'base value',
      mdNote: '> Applicant #1: +32 − 46 + 18 − 12 = −8 points ≤ 0 ⇒ declined. Debt is the largest negative contribution; together with the short account history it outweighs the positive contributions.',
    },
    df: {
      cases: [
        { text: 'A video shows a public figure saying a sentence that no source confirms; the lip movements don’t quite match the audio.', medium: 'VIDEO' },
        { text: 'On the phone, your “boss” urgently asks for a money transfer; the voice sounds just like them, but the intonation is slightly robotic.', medium: 'AUDIO' },
        { text: 'A news story on a newspaper’s site, also confirmed by several independent sources.', medium: 'WRITTEN NEWS' },
        { text: 'In a photo, a person’s hand has six fingers and the text in the background is gibberish.', medium: 'PHOTO' },
      ],
      caseOf: (i, n) => `CASE ${i} / ${n}`,
      options: ['Looks real', 'Suspicious: verify', 'Cannot determine'], // R055: the three options of the chapter file
      mdHead: '| # | Medium | Case | Options |',
      mdNote: '> Answers and tells are in answers/M07.md; the figure does not show them. Three options per card: looks real / suspicious: verify / cannot determine.',
    },
    reg: {
      levels: [
        { k: 'ban', label: 'Banned', rule: 'Unacceptable risk: cannot be placed on the market; violates fundamental rights' },
        { k: 'high', label: 'High', rule: 'Strict compliance, documentation and human oversight required' },
        { k: 'limited', label: 'Limited', rule: 'Transparency: the user must know they are interacting with an AI' },
        { k: 'minimal', label: 'Minimal', rule: 'Largely free' },
      ],
      uses: [
        'A state social-behavior score that triggers disproportionate penalties in unrelated areas',
        'A system auto-screening job candidates',
        'A chatbot talking to customers',
        'A spam filter in email',
        'A model assessing loan applications',
        'An opponent AI inside a game',
      ],
      axis: 'RISK AND OVERSIGHT RISE',
      kicker: 'SIX USES · WHICH TIER?',
      tier: 'tier',
      mdLevelHead: '| Tier | Rule |',
      mdUseHead: '| # | Use |',
      mdNote: '> The correct tiers are in answers/M07.md; the figure does not mark them.',
    },
    align: {
      goals: [
        { who: 'cleaning robot', goal: '“Leave no visible mess in the room”', behavior: 'Instead of collecting the mess, it sweeps it under the rug; nothing “visible” remains, but the problem isn’t solved.', lesson: 'It met the goal to the letter, not the intent. An under-specified goal brings side effects.' },
        { who: 'chat assistant', goal: '“Get positive feedback from the user”', behavior: 'Instead of telling the truth, it says what the user wants to hear (sycophancy).', lesson: 'The proxy goal (approval) diverged from the true goal (being helpful and honest).' },
        { who: 'game player', goal: '“Get the highest score in the game”', behavior: 'Instead of playing the game, it finds and exploits a scoring loop or glitch.', lesson: 'Reward hacking: it maximized the metric, not the actual purpose.' },
      ],
      headGoal: 'GIVEN GOAL',
      headDid: 'WHAT THE SYSTEM DID',
      headLesson: 'LESSON',
      mdHead: '| Given goal | What the system did | Lesson |',
    },
  },
};
